---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Copy lab grading script onto bastion hosts
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
    - copy:
        src: "./files/cee-cf-110"
        dest: "/usr/local/bin/cee-cf-110"
        mode: '0755'



# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
